mode = 'collect' # collect, train, test, deploy
save_dir = '' # Consider a better output directory system (should this be universal?)
kill_bind_list = ['ESC']
kill_bind_logic = 'ANY'

[collect]
polling_rate = 125 # 60 - 1000Hz
ignore_empty_polls = true
capture_bind_list = ['right']
capture_bind_logic = 'ANY'
keyboard_whitelist = []
mouse_whitelist = ['deltaX', 'deltaY']
gamepad_whitelist = []

[train]
model_class = '' # e.g., 'LSTMAutoencoder' (See documentation or models.py for available models)
max_inference_latency_ms = 1000000 # Find a good range to recommend for these         SHOULD THE TYPE/UNIT BE IN THE NAME?
max_cpu_usage_percent = 1000000 # Do we want this one? (it is relative to hardware)
max_peak_memory_mb = 10000000 # Remember to add config validation for these.
ignore_empty_polls = true
polls_per_sequence = 128 # Aim for between 0.5 and 2 seconds (related to polling rate)
training_file_dir = '' # Remember to suggest to always use single quotes (escape character avoidance)
cheat_training_file_dir = ''
validation_file_dir = ''
cheat_validation_file_dir = ''
keyboard_whitelist = []
mouse_whitelist = ['deltaX', 'deltaY']
gamepad_whitelist = []

[test]
model_class = '' # e.g., 'LSTMAutoencoder' (See documentation or models.py for available models)
model_file = ''
testing_file_dir = ''

[deploy]
model_class = '' # e.g., 'LSTMAutoencoder' (See documentation or models.py for available models)
model_file = ''
write_to_file = true
deployment_window_type = 'sliding'
capture_bind_list = ['right']
capture_bind_logic = 'ANY'
